services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    image: user_name/project_name-backend:latest
    container_name: fastapi-backend
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    command: sh -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    # env_file:   # if exist `.env` file
    #   - ./backend/.env
    environment:
      DATABASE_URL: postgresql://app_user:app_password@db:5432/app_db
    depends_on:
      - db

volumes:
  postgres_data:
