name: Feature Request
description: Please file a feature request with details to help us evaluate it.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: feature
    attributes:
      label: Feature
      description: |
        Share a clear and detailed description of your idea.
      placeholder: Tell us what you would like to see!
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Use Case
      description: |
        Explain why this feature is useful or what problem it solves.
      placeholder: Tell us why this matters or what it fixes!
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context or screenshots about the feature request here.
    validations:
      required: false
